### ISSUE TITLE
Question: Is this being maintained?

### ISSUE THREAD

**Issue by shamil614** [jakesgordon/rack-rabbit#9]
I see that there's not much activity on the project.  It's really interesting and I'm just curious if there's anyone using it in production?

**Comment by jakesgordon** [comment]
I'm no longer using it in a production environment (just because I'm no longer using RabbitMQ), although that might change with my new project.

I don't have much time to actively maintain the project at the moment but I will fix critical bugs if they come in, and review pull requests. It's reasonably complete and I believe works reasonably well but I've never really promoted it in anyway so it's not a particularly well known project.

**Comment by shamil614** [comment]
Ok. Thanks for the update.  Nice work on the project.  I'm just trying to decide if we should adopt it.
